-- Run this file in the Supabase SQL editor.
create table if not exists zones (
  id bigint generated by default as identity primary key,
  name text not null,
  latitude double precision not null,
  longitude double precision not null,
  rainfall_24h double precision not null default 0,
  rainfall_7d double precision not null default 0,
  elevation double precision not null default 0,
  drainage_score double precision not null default 50,
  population_density double precision not null default 0,
  population integer not null default 0,
  historical_flood_count integer not null default 0,
  citizen_report_count integer not null default 0,
  risk_score double precision not null default 0,
  risk_category text not null default 'LOW',
  area_km2 double precision not null default 2.5
);

create table if not exists risk_assessments (
  id bigint generated by default as identity primary key,
  zone_id bigint not null references zones(id),
  score double precision not null,
  category text not null,
  confidence double precision not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists citizen_reports (
  id bigint generated by default as identity primary key,
  zone_id bigint references zones(id),
  latitude double precision not null,
  longitude double precision not null,
  water_level_cm double precision not null default 0,
  description text not null,
  photo_url text,
  severity text not null,
  credible boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists resources (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  latitude double precision not null,
  longitude double precision not null,
  quantity integer not null default 0,
  available integer not null default 0,
  road_status text not null default 'OPEN'
);

create table if not exists emergencies (
  id bigint generated by default as identity primary key,
  message_id text not null unique,
  emergency_type text not null,
  latitude double precision not null,
  longitude double precision not null,
  people integer not null default 0,
  vulnerable text not null default '',
  priority text not null,
  status text not null default 'QUEUED',
  assigned_resource_id bigint references resources(id),
  ttl integer not null default 10,
  hop_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists recommendations (
  id bigint generated by default as identity primary key,
  zone_id bigint references zones(id),
  priority integer not null,
  action text not null,
  resource_type text not null,
  quantity integer not null default 0,
  reason text not null,
  created_at timestamptz not null default now()
);

create table if not exists shelters (
  id bigint generated by default as identity primary key,
  name text not null,
  latitude double precision not null,
  longitude double precision not null,
  capacity integer not null default 0,
  available_capacity integer not null default 0
);

create table if not exists roads (
  id bigint generated by default as identity primary key,
  name text not null,
  zone_id bigint not null references zones(id),
  status text not null default 'OPEN'
);

create table if not exists sync_queue (
  id bigint generated by default as identity primary key,
  payload_type text not null,
  payload jsonb not null,
  status text not null default 'PENDING',
  created_at timestamptz not null default now()
);

create table if not exists weather_observations (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null,
  source text not null,
  latitude double precision,
  longitude double precision,
  variables jsonb not null default '{}'::jsonb,
  quality_flags jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (source, observed_at, latitude, longitude)
);

create table if not exists grid_observations (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null,
  source text not null,
  variable text not null,
  units text,
  shape integer[] not null,
  values jsonb not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (source, observed_at, variable)
);

create table if not exists ingestion_runs (
  id bigint generated by default as identity primary key,
  source text not null,
  status text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  files_processed integer not null default 0,
  error text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists alert_deliveries (
  id bigint generated by default as identity primary key,
  alert_key text not null,
  zone_id bigint references zones(id),
  channel text not null,
  destination text not null,
  payload jsonb not null,
  status text not null default 'PENDING',
  attempts integer not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  delivered_at timestamptz,
  unique (alert_key, channel, destination)
);

create index if not exists zones_risk_idx on zones (risk_category, risk_score desc);
create index if not exists reports_created_idx on citizen_reports (created_at desc);
create index if not exists weather_observed_idx on weather_observations (observed_at desc, source);
create index if not exists grid_observed_idx on grid_observations (observed_at desc, source, variable);
create index if not exists ingestion_runs_idx on ingestion_runs (started_at desc, source);
create index if not exists alert_deliveries_idx on alert_deliveries (created_at desc, status);
alter table zones enable row level security;
alter table risk_assessments enable row level security;
alter table citizen_reports enable row level security;
alter table emergencies enable row level security;

drop policy if exists zones_public_read on zones;
create policy zones_public_read on zones for select to anon, authenticated using (true);
drop policy if exists zones_backend_update on zones;
create policy zones_backend_update on zones for update to anon, authenticated using (true) with check (true);
drop policy if exists risk_assessments_backend_insert on risk_assessments;
create policy risk_assessments_backend_insert on risk_assessments for insert to anon, authenticated with check (true);
drop policy if exists reports_public_read on citizen_reports;
create policy reports_public_read on citizen_reports for select to anon, authenticated using (true);
drop policy if exists reports_public_insert on citizen_reports;
create policy reports_public_insert on citizen_reports for insert to anon, authenticated with check (true);
drop policy if exists emergencies_public_read on emergencies;
create policy emergencies_public_read on emergencies for select to anon, authenticated using (true);
drop policy if exists emergencies_public_insert on emergencies;
create policy emergencies_public_insert on emergencies for insert to anon, authenticated with check (true);