selection_metric: csi
fit_split: validation
thunderstorm: {"+2h": 0.5, "+3h": 0.5, "+4h": 0.5, "+5h": 0.5, "+6h": 0.5}
cloudburst: {"+2h": 0.5, "+3h": 0.5, "+4h": 0.5, "+5h": 0.5, "+6h": 0.5}
flash_flood: {"+2h": 0.32, "+3h": 0.3, "+4h": 0.3, "+5h": 0.3, "+6h": 0.32}
